language: python
python:
{%- if cookiecutter.Python_version == 'Python 2 and 3' or cookiecutter.Python_version == 'Python 2' %}
  - "2.7"
{%- endif %}
{%- if cookiecutter.Python_version == 'Python 3' or cookiecutter.Python_version == 'Python 2 and 3' %}
  - "3.4"
  - "3.5"
  - "3.6"
{%- endif %}

# command to install dependencies
install:
  - pip install -r requirements.txt

pytest -s
